### ISSUE TITLE
overriding the default templates

### ISSUE THREAD

**Issue by alexanderj1988** [agreatfool/grpc_tools_node_protoc_ts#16]
the default templates work fine, but we want to use our own templates, which provide additional interfaces
which can be implemented and injected.

Is there a possability to add a template argument/env variable in the codegen-script to override the default folder?

regards Alex

**Comment by agreatfool** [comment]
Hi,

Since the requirement seems not common, and not easy to expose the template path dir directly to end users. I suggest you could replace the template installed in the node_modules.

The plugin is installed here:
```bash
./node_modules/grpc_tools_node_protoc_ts
```

The plugin bin file is here:
```bash
./node_modules/.bin/protoc-gen-ts
```

And the template you need to replace is here:
```bash
./node_modules/grpc_tools_node_protoc_ts/build/lib/template/**/*.hbs
```

Just have a try. If any question, contacts me here.
