### ISSUE TITLE
No details type in the ServiceError of client 

### ISSUE THREAD

**Issue by CatsMiaow** [agreatfool/grpc_tools_node_protoc_ts#36]
```ts
getBook(request: book_pb.GetBookRequest, callback: (error: grpc.ServiceError | null, response: book_pb.Book) => void): grpc.ClientUnaryCall;
```
grpc.ServiceError type is not in details

https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/src/server.js#L50
The actual response contains details

https://grpc.io/grpc/node/grpc.html#~StatusObject__anchor
https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/call.ts#L97
Client errors should use details

https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/call.ts#L13
```ts
export type ServiceError = StatusObject & Error;
```
This is the client error type used by grpc-js

**Comment by agreatfool** [comment]
Hi @CatsMiaow,

I just didn't got your idea.
Did you mean the code below (as mentioned in your issue description) should not use error type `grpc.ServiceError`?

```typescript
getBook(request: book_pb.GetBookRequest, callback: (error: grpc.ServiceError | null, response: book_pb.Book) => void): grpc.ClientUnaryCall;
```

**Comment by CatsMiaow** [comment]
Yes, the type of error the client responds to should include 'details'.
It would be better to use the ServiceError( StatusObject & Error ) type used in grpc-js.

For example, if the server responds with an error
```ts
return callback({
  code: grpc.status.INVALID_ARGUMENT,
  message: "HelloWorld"
});
```
The error.message returns "3 INVALID_ARGUMENT: HelloWorld"
The error.details returns "HelloWorld"

**Comment by agreatfool** [comment]
Got your idea.

As there is only one Error definition in grpc index.d.ts, and also considering the information you provided like:

- https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/call.ts#L97
- https://grpc.io/grpc/node/grpc.html#~StatusObject__anchor

We can assume that the Error type officially defined shall be `ServiceError`.

Currently, your main issue is: The definition of ServiceError provided by official index.d.ts ([link](https://github.com/grpc/grpc-node/blob/22a04a4bf159f809f2c8439fdfbaa42f52ee8945/packages/grpc-native-core/index.d.ts#L556-L570)) missed a field `details`.

I think you should raise an issue in grpc-node repo: https://github.com/grpc/grpc-node/issues. Since the owner of `ServiceError` definition is grpc-node repo, not here.

**Comment by CatsMiaow** [comment]
Thank, it seems to be fixed in the referenced issue.
